#!/kolab/bin/perl -w
use strict;

use Getopt::Long;
use Kolab::DirServ;
use Kolab;
use Kolab::Util;
use vars qw($server $user $password);

GetOptions(
    "server=s"      => \$server,
    "user=s"        => \$user,
    "password=s"    => \$password
);

#easy default values for development
$server = $Kolab::config{'dirserv_mailbox_server'} if !$server;
$user = $Kolab::config{'dirserv_mailbox_user'} if !$user;
$password = $Kolab::config{'dirserv_mailbox_password'} if !$password;

Kolab::DirServ::handleNotifications($server, $user, $password);
