#!@l_prefix@/bin/perl

##
##  Copyright (c) 2003  Code Fusion cc
##
##    Writen by Stuart Bingë  <s.binge@codefusion.co.za>
##    Portions based on work by the following people:
##
##      (c) 2003  Tassilo Erlewein  <tassilo.erlewein@erfrakon.de>
##      (c) 2003  Martin Konold     <martin.konold@erfrakon.de>
##      (c) 2003  Achim Frank       <achim.frank@erfrakon.de>
##
##
##  This  program is free  software; you can redistribute  it and/or
##  modify it  under the terms of the GNU  General Public License as
##  published by the  Free Software Foundation; either version 2, or
##  (at your option) any later version.
##
##  This program is  distributed in the hope that it will be useful,
##  but WITHOUT  ANY WARRANTY; without even the  implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
##  General Public License for more details.
##
##  You can view the  GNU General Public License, online, at the GNU
##  Project's homepage; see <http://www.gnu.org/licenses/gpl.html>.
##

use strict;
use Getopt::Std;
use vars qw($opt_o);

getopts('vol:');

if ($opt_o) {
    print "NOTE: USE OF THIS SCRIPT IS DEPRECATED. Please use `@l_prefix@/sbin/kolabconf' in the future.\n";
    system("@l_prefix@/sbin/kolabconf");
} else {
    print "NOTE: USE OF THIS SCRIPT IS DEPRECATED. Please use `@l_prefix@/sbin/kolabd' in the future.\n";
    system("@l_prefix@/sbin/kolabd");
}
