#! /bin/sh

set -e

add_kolab_system_users() {
	if ! getent passwd kolab >/dev/null; then
		adduser --group --system --no-create-home --gecos "kolab user" \
			--home /var/lib/kolab kolab;
	fi
}

fixperms() {
	dpkg-statoverride --list /var/lib/kolab >/dev/null || \
		dpkg-statoverride --update --add kolab kolab 0775 /var/lib/kolab
}

create_log() {
	if ! [ -d /var/log/kolab ] ; then
		echo "Creating log directory for Kolab"
		mkdir -p /var/log/kolab
	fi
}

create_cachefiles() {
	if ! [ -f /var/lib/kolab/mailbox-uidcache.db ] ; then
		echo "Creating Mailbox UID cache file"
		/usr/sbin/kolabdcachetool mbox flush
	fi
	if ! [ -f /var/lib/kolab/graveyard-tscache.db ] ; then
		echo "Creating Graveyard files"
		/usr/sbin/kolabdcachetool gyard flush
	fi
}

case "$1" in
	configure)
		add_kolab_system_users
		fixperms
		create_log
		create_cachefiles
		;;
	abort-upgrade|abort-deconfigure|abort-remove)
		:
		;;
	*)
		echo "Called with unknown argument $1, bailing out."
		exit 1
		;;
esac

#DEBHELPER#

