.TH undocumented 1 2006-08-23 Kolab
.SH NAME
undocumented \- Kolab groupware suite
.SH SYNOPSIS
\fBundocumented\fR
.SH DESCRIPTION
This program belongs to the Kolab groupware suite, but it does not have
a useful manual page of its own.  Please see the documentation under
\fI/usr/share/doc/kolabd/\fR for more information.
