#!/bin/sh

upackage=kolabd
dpackage=kolabd
version=$2
file=$3

rpm2cpio "$file" | \
cpio --extract --quiet --to-stdout "${upackage}-*.tar.bz2" | \
bunzip2 --stdout | gzip \
> "${dpackage}_${version}.orig.tar.gz"
rm "$file"
